CREATE TABLE public.adm_usuarios (
    user_id bigint NOT NULL,
    user_apellidos character varying(150),
    user_correo character varying(150),
    user_dui character varying(9),
    user_estado numeric(1,0) DEFAULT 1,
    user_fch_modifica date,
    user_fch_nac date,
    user_fch_registro date,
    user_nombres character varying(150),
    user_password character varying(250) NOT NULL,
    user_sexo text,
    user_telefono character varying(12),
    user_username character varying(100) NOT NULL,
    user_usuario_modifica character varying(100),
    user_usuario_registra character varying(100),
    user_rol character varying(50) DEFAULT 'CDSF-ACCESS'::character varying
);
CREATE TABLE public.cliente (
    id bigint NOT NULL,
    departamento character varying(255),
    direccion character varying(255),
    email character varying(255),
    estado character varying(255),
    fecha_registro date,
    giro character varying(255),
    municipio character varying(255),
    nit character varying(255),
    nombre character varying(255),
    nrc character varying(255),
    telefono character varying(255),
    tipo_cliente character varying(255),
    tipo_documento character varying(255)
);
ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.contrato (
    id bigint NOT NULL,
    estado character varying(255),
    fecha_creacion date,
    fecha_inicio date,
    fecha_proxima_facturacion date,
    honorarios_pactados numeric(38,2),
    notas character varying(255),
    tipo_facturacion character varying(255),
    cliente_id bigint
);
ALTER TABLE public.contrato ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contrato_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.contrato_servicio (
    id bigint NOT NULL,
    precio_acordado numeric(38,2),
    contrato_id bigint NOT NULL,
    servicio_id bigint NOT NULL
);
ALTER TABLE public.contrato_servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contrato_servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.detalle_factura (
    id bigint NOT NULL,
    cantidad numeric(38,2),
    descripcion character varying(255),
    descuento numeric(38,2),
    num_item integer,
    precio_unitario numeric(38,2),
    tipo_item character varying(255),
    unidad_medida character varying(255),
    venta_exenta numeric(38,2),
    venta_gravada numeric(38,2),
    venta_no_sujeta numeric(38,2),
    factura_id bigint
);
ALTER TABLE public.detalle_factura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_factura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.dte_catalogo (
    dtca_id bigint NOT NULL,
    dtca_cap bigint,
    dtca_cax character varying(10),
    dtca_cod character varying(18),
    dtca_des character varying(250),
    dtca_est smallint,
    dtca_fec timestamp(6) with time zone,
    dtca_usr character varying(10)
);
CREATE TABLE public.dte_correlativo (
    dtco_id bigint NOT NULL,
    dtco_tipo_dte character varying(2) NOT NULL,
    dtco_ultimo bigint NOT NULL
);
ALTER TABLE public.dte_correlativo ALTER COLUMN dtco_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dte_correlativo_dtco_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.dte_parametro (
    dtpa_id bigint NOT NULL,
    dtpa_descripcion character varying(70) NOT NULL,
    dtpa_estado smallint,
    dtpa_nombre character varying(60) NOT NULL,
    dtpa_val character varying(500) NOT NULL
);
ALTER TABLE public.dte_parametro ALTER COLUMN dtpa_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dte_parametro_dtpa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.dte_token (
    dtto_id bigint NOT NULL,
    dtto_fec timestamp(6) with time zone,
    dtto_message character varying(20),
    dtto_res character varying(600),
    dtto_status character varying(20),
    dtto_token character varying(500)
);
ALTER TABLE public.dte_token ALTER COLUMN dtto_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dte_token_dtto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.factura (
    id bigint NOT NULL,
    codigo_generacion character varying(255),
    condicion_pago character varying(255),
    descuento numeric(38,2),
    estado character varying(255),
    estado_dte character varying(255),
    fecha_emision timestamp(6) without time zone,
    fecha_pago date,
    fecha_vencimiento date,
    iva_percibido numeric(38,2),
    iva_retenido numeric(38,2),
    monto_total numeric(38,2),
    notas character varying(255),
    numero_control character varying(255),
    numero_factura character varying(255),
    periodo_facturado character varying(255),
    plazo_credito integer,
    respuestamh character varying(255),
    sello_recepcion character varying(255),
    subtotal_exento numeric(38,2),
    subtotal_gravado numeric(38,2),
    subtotal_no_sujeto numeric(38,2),
    tipo_dte character varying(255),
    cliente_id bigint,
    contrato_id bigint,
    proyecto_id bigint
);
ALTER TABLE public.factura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.factura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.proyecto (
    id bigint NOT NULL,
    categoria character varying(255),
    descripcion character varying(255),
    estado character varying(255),
    facturado boolean,
    fecha_creacion date,
    fecha_estimada_fin date,
    fecha_fin date,
    fecha_inicio date,
    nombre character varying(255),
    notas character varying(255),
    porcentaje_avance integer,
    presupuesto numeric(38,2),
    cliente_id bigint
);
ALTER TABLE public.proyecto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proyecto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.servicio (
    id bigint NOT NULL,
    categoria character varying(255),
    descripcion character varying(255),
    nombre character varying(255),
    periodicidad character varying(255),
    precio numeric(38,2)
);
ALTER TABLE public.servicio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.servicio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.adm_usuarios
    ADD CONSTRAINT adm_usuarios_pkey PRIMARY KEY (user_id);
ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.contrato
    ADD CONSTRAINT contrato_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.contrato_servicio
    ADD CONSTRAINT contrato_servicio_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.detalle_factura
    ADD CONSTRAINT detalle_factura_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.dte_catalogo
    ADD CONSTRAINT dte_catalogo_pkey PRIMARY KEY (dtca_id);
ALTER TABLE ONLY public.dte_correlativo
    ADD CONSTRAINT dte_correlativo_pkey PRIMARY KEY (dtco_id);
ALTER TABLE ONLY public.dte_parametro
    ADD CONSTRAINT dte_parametro_pkey PRIMARY KEY (dtpa_id);
ALTER TABLE ONLY public.dte_token
    ADD CONSTRAINT dte_token_pkey PRIMARY KEY (dtto_id);
ALTER TABLE ONLY public.factura
    ADD CONSTRAINT factura_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT proyecto_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.servicio
    ADD CONSTRAINT servicio_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.dte_correlativo
    ADD CONSTRAINT uk_dte_correlativo_tipo UNIQUE (dtco_tipo_dte);
ALTER TABLE ONLY public.factura
    ADD CONSTRAINT uk_factura_codigo_generacion UNIQUE (codigo_generacion);
ALTER TABLE ONLY public.factura
    ADD CONSTRAINT uk_factura_numero_control UNIQUE (numero_control);
ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fk2602efsrpmevi8yxg464stfn5 FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);
ALTER TABLE ONLY public.contrato_servicio
    ADD CONSTRAINT fkd4m8j7hh6nq0crrpbe40jwtfu FOREIGN KEY (contrato_id) REFERENCES public.contrato(id);
ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fke82w9k9fb7gpk3wuhgmfekqpk FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id);
ALTER TABLE ONLY public.factura
    ADD CONSTRAINT fkhrgglc2vv23cgd9xn6vnj14qn FOREIGN KEY (contrato_id) REFERENCES public.contrato(id);
ALTER TABLE ONLY public.contrato
    ADD CONSTRAINT fkivcfejpecgmfnhk1p8cav4956 FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);
ALTER TABLE ONLY public.proyecto
    ADD CONSTRAINT fkj2p2goqb0xk955fy0i6e1qquc FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);
ALTER TABLE ONLY public.contrato_servicio
    ADD CONSTRAINT fklvxrco91y6u1990miff8gykwq FOREIGN KEY (servicio_id) REFERENCES public.servicio(id);
ALTER TABLE ONLY public.detalle_factura
    ADD CONSTRAINT fkucgyfvfujw8g2tt3c6fdkxai FOREIGN KEY (factura_id) REFERENCES public.factura(id);
