-- ============================================================
-- Registro del tiempo dedicado a cada caso.
--
-- Es la unidad con la que factura un bufete y hasta ahora no existía: un
-- proyecto tenía presupuesto y un booleano de facturado, lo que solo
-- permite cobrar precio cerrado.
--
-- tarifa_hora aparece dos veces a propósito. En 'proyecto' es el valor por
-- defecto del caso; en 'registro_horas' es la tarifa que de verdad se
-- aplicó, copiada al registrar. Las tarifas suben, y el trabajo de marzo
-- no puede reprecificarse porque en septiembre se acordara otra cosa.
-- ============================================================

ALTER TABLE public.proyecto
    ADD COLUMN tarifa_hora numeric(38,2);

CREATE TABLE public.registro_horas (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proyecto_id     bigint NOT NULL,
    fecha           date,
    horas           numeric(38,2),
    descripcion     varchar(255),
    usuario         varchar(255),
    tarifa_hora     numeric(38,2),
    facturable      boolean,
    factura_id      bigint,

    -- Auditoría, como el resto de entidades de negocio (V2)
    creado_por      character varying(60),
    creado_en       timestamp(6) without time zone,
    modificado_por  character varying(60),
    modificado_en   timestamp(6) without time zone,

    CONSTRAINT fk_registro_horas_proyecto
        FOREIGN KEY (proyecto_id) REFERENCES public.proyecto(id),
    -- Sin ON DELETE: una factura no se borra, se anula, así que el registro
    -- nunca queda apuntando al vacío.
    CONSTRAINT fk_registro_horas_factura
        FOREIGN KEY (factura_id) REFERENCES public.factura(id)
);

-- "El detalle de horas de este caso" es la consulta de cada día.
CREATE INDEX idx_registro_horas_proyecto ON public.registro_horas (proyecto_id);

-- "Qué queda por cobrar" recorre solo los pendientes: sin este índice
-- barre todo el histórico del caso para descartarlo.
CREATE INDEX idx_registro_horas_pendientes
    ON public.registro_horas (proyecto_id)
    WHERE factura_id IS NULL;
