-- ============================================================
-- Libro de compras.
--
-- Es la contrapartida del libro de ventas, que ya existía: sin registrar
-- lo comprado no hay crédito fiscal que oponer al débito, y la
-- liquidación mensual del IVA no se puede cerrar.
--
-- Registra las compras del propio despacho. Llevar los libros de sus
-- clientes exigiría un emisor por empresa, que es una decisión de
-- producto todavía abierta.
-- ============================================================

CREATE TABLE public.compra (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha             date,
    tipo_documento    varchar(2),
    numero_documento  varchar(255),
    proveedor_nombre  varchar(255),
    proveedor_nit     varchar(255),
    proveedor_nrc     varchar(255),
    tipo_operacion    varchar(20),
    descripcion       varchar(255),
    monto_exento      numeric(38,2),
    monto_gravado     numeric(38,2),
    credito_fiscal    numeric(38,2),
    total             numeric(38,2),

    creado_por        character varying(60),
    creado_en         timestamp(6) without time zone,
    modificado_por    character varying(60),
    modificado_en     timestamp(6) without time zone,

    -- Registrar dos veces el mismo documento del mismo proveedor infla el
    -- crédito fiscal, que es un error caro y difícil de ver en una lista
    -- de cien líneas. Lo impide la base, no solo el servicio.
    CONSTRAINT uk_compra_proveedor_documento UNIQUE (proveedor_nit, numero_documento)
);

-- El libro siempre se consulta por periodo.
CREATE INDEX idx_compra_fecha ON public.compra (fecha);
